In [31]:
#import load_model class for loading h5 file
from tensorflow.keras.models import load_model
#import image class to process the images
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.inception_v3 import preprocess_input
import numpy as np

In [22]:
#load saved model file
model=load_model('updated-xception-diabetic-retinopathy.h5')

In [23]:
#load one random image from local system
img=image.load_img(r'PDR.jpg',target_size=(299,299))

In [24]:
#convert image to array format
x=image.img_to_array(img)

In [25]:
import matplotlib.pyplot as plt
x.shape

(299, 299, 3)

In [26]:
import numpy as np
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 299, 299, 3)

In [27]:
model.predict(img_data)

1/1 [==============================] - 1s 1s/step


array([[9.9970537e-01, 1.0556175e-11, 2.9463277e-04, 5.7209237e-11,
        1.4119197e-12]], dtype=float32)

In [28]:
output=np.argmax(model.predict(img_data), axis=1)

1/1 [==============================] - 0s 389ms/step


In [29]:
output==0,output==1,output==2,output==3,output==4

(array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]))

In [30]:
index=['No Diabetic Retinopathy', 'Mild DR', 'Moderate DR', 'Severe DR', 'Proliferative DR']
result = str(index[output[0]])
result

'No Diabetic Retinopathy'